version: '3.7'

services:
  postgres:
    image: postgres:16.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psqladmin -d educar"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: educar
      POSTGRES_USER: psqladmin
      POSTGRES_PASSWORD: pgadmin
    ports:
      - 15432:5432
    networks:
      - educar_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/educar
      KC_DB_USERNAME: psqladmin
      KC_DB_PASSWORD: pgadmin
    ports:
      - 18080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - educar_network

volumes:
  pg_data:
    driver: local

networks:
  educar_network:
    driver: bridge